server:
  port: 5000
spring:
  application:
    name: app-eureka
  security:
    user:
      name: ${spring.application.name}
      password: ${spring.application.name}
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: eureka0
server:
  port: 5000
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka, http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:5001/eureka
---
spring:
  profiles: eureka1
server:
  port: 5001
eureka:
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka, http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:5002/eureka
---
spring:
  profiles: eureka2
server:
  port: 5002
