server:
  port: 5020
spring:
  application:
    name: app-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://app-eureka:app-eureka@127.0.0.1:5000/eureka
    register-with-eureka: true #是否将自己当做服务注册
    fetch-registry: true #是否注册信息
  instance:
    prefer-ip-address: true
s-spring-cloud:
  dynamic-call:
    enabled: false
